/** Shared Monaco options used across dialogs and the adaptive code editor. */
export const DEFAULT_MONACO_CODE_EDITOR_OPTIONS = {
  minimap: { enabled: false },
  fontSize: 14,
  fontFamily: 'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, "Liberation Mono", monospace',
  lineNumbers: 'on' as const,
  roundedSelection: true,
  scrollBeyondLastLine: false,
  automaticLayout: true,
  formatOnPaste: true,
  formatOnType: true,
  renderWhitespace: 'none' as const,
  wordWrap: 'on' as const,
  folding: true,
  suggestOnTriggerCharacters: true,
  quickSuggestions: true,
  renderLineHighlight: 'all' as const,
  scrollbar: {
    vertical: 'visible' as const,
    horizontal: 'visible' as const,
    useShadows: false,
    verticalScrollbarSize: 10,
    horizontalScrollbarSize: 10,
  },
  contextmenu: true,
  copyWithSyntaxHighlighting: false,
  multiCursorModifier: 'alt' as const,
  accessibilitySupport: 'on' as const,
  mouseWheelZoom: true,
  quickSuggestionsDelay: 0,
  occurrencesHighlight: 'singleFile' as const,
  wordBasedSuggestions: 'currentDocument' as const,
  suggest: {
    showWords: true,
    showSnippets: true,
    showClasses: true,
    showFunctions: true,
    showVariables: true,
    showProperties: true,
    showColors: true,
    showFiles: true,
    showReferences: true,
    showFolders: true,
    showTypeParameters: true,
    showEnums: true,
    showConstructors: true,
    showDeprecated: true,
    showEnumMembers: true,
    showKeywords: true,
  },
} as const
